### ISSUE TITLE
Inconsistency in numbering

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#1]
The draft documents refer to JSON-LD 1.1. However, the charter text says:

> The group will maintain and advance the Test Suite allowing for continued testing of JSON-LD 1.0 implementations in addition to JSON-LD processors operating both in legacy and 2.0 modes.

And the items in [2.1](https://json-ld.github.io/charter/#deliverables) also refer to 2.0.

I personally prefer 1.1, because the changes are not really fundamental, but that is a judgement call. But the CG draft and the charter should be consistent.

**Comment by msporny** [comment]
Can we please call it JSON-LD 1.1? Digital Bazaar is far less likely to support a charter talking about JSON-LD 2.0 (for purely messaging reasons).

Let's save JSON-LD 2.0 for when we need to break backward compatibility in some way or do major changes.

Happy to discuss further, but JSON-LD 2.0 sounds very different (from a public messaging perspective) than what we were had assumed this work was about (which was a quick rev of the spec to reflect highly desired features). We're very wary of scope creep... we've got a good thing going, let's not set the bar for the next revision that high.

**Comment by gkellogg** [comment]
The 2.0 version is speculative based on https://github.com/json-ld/json-ld.org/issues/548. Semantic Versioning suggests that any change that causes aomethng to break should result in a new major version. By intention, a 1.0 processor encountering @version in a context will break.

I am sympathetic to keeping it at 1.1, but concern was expressed at TPAC about this. I’d love to see counter arguments on that issue. IIRC, both @iherman and @msporny we’re present for those discussions.

It’s reasonable to keep the charter consistent with the current numbering, and we could defer the issue to the WG.

**Comment by iherman** [comment]
@gkellogg 

>  By intention, a 1.0 processor encountering @Version in a context will break.

This is true, but I do not think that is a reason to go up to a major version. I think, as I said in #2, the main point is that an 1.1 processor can process an 1.0 content without loss and change. For me, that is perfectly enough to say it is 1.1.

To be honest, I do not remember the numbering/versioning discussion at TPAC...

**Comment by iherman** [comment]
> It’s reasonable to keep the charter consistent with the current numbering, and we could defer the issue to the WG.

👍 to that.
