### ISSUE TITLE
Reference to the DWPB WG document

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#15]
The document includes, in the scope section

> The scope of work is limited by the principle of consistency with the objectives for describing data on the World Wide Web as expressed in Data on the Web Best Practices.

I do not really understand what this means. The DWPB doesn't explicitly define a "principle of consistency" to refer to; referring to such a document as a general statement does not really mean anything. I propose to remove the sentence. (The next sentence should also be slightly rephrased then.)

**Comment by gkellogg** [comment]
From what I can tell, "the principle of consistency" doesn't come from DWPB, but is a separate phrase (from [accounting?](https://www.accountingtools.com/articles/2017/5/15/the-consistency-principle)) used to indicate the the principles used within a specification should be self-consistent, which just seems like a reasonable perspective to go about writing specifications.

WRT referencing DWPB, JSON-LD is an attempt to provide a well-grounded basis for describing data on the web based on principles that JSON developers have organically come to. In general, the best practices espoused in JSON-LD documents should conform why those from DWPB.

I've given this to @azaroth42, though, to better describe what he meant by the change.

**Comment by azaroth42** [comment]
Oh, I didn't mean to reference a particular "Principle", just the notion. Will edit :)
