### ISSUE TITLE
Review of Philippe le Hégaret, on behalf of W3M

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#19]
(Copying, with permission, PlH's mail.)

Hi Ivan,

I only have minor comments.

I presume your 10% comes from the POE leftover.

Section 3.2 can be removed.

Use Process 2018 and Patent Policy 2017 for the links (see https://w3c.github.io/charter-drafts/charter-template.html )

Philippe

**Comment by BigBlueHat** [comment]
From the looks of https://github.com/json-ld/charter/commit/c89242ddd1b05002e796e07090ae913f0612fd7b you've already got these fixed, amiright @iherman ?

**Comment by iherman** [comment]
Indeed I have
