### ISSUE TITLE
Backward compatibility in the charter

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#2]
I believe the charter should make a stronger statement somewhere on the backward compatibility of JSON-LD 1.1 vs. JSON-LD 1.0. Maybe at the end of section 1 (right before 1.1) we could add something like:

> The specifications developed by this Working Group MUST be strictly backward compatible with the ones published in 2014. Ie, any valid [JSON-LD 1.0](https://www.w3.org/TR/2014/REC-json-ld-20140116/) document MUST be valid JSON-LD 1.1. Furthermore, a JSON-LD 1.1 processor MUST produce the exact same linked data representation as its JSON-LD 1.0 processor counterpart.

I am not 100% sure how to say that the results are equivalent. If we use RDF then the situation is clearer: the RDF graphs must be equivalent in the RDF Semantics sense. But, though mathematically precise, I am not sure it is the right terminology for the charter...

**Comment by gkellogg** [comment]
There are some areas where a 1.1 processor, operating in 1.0 mode, will compact differently. Notably, compact IRI generation was seriously broken, and it's been "fixed" (see json-ld/json-ld.org#405).

Note that expanding and turning JSON-LD into N-Quads is not affected, only compaction for a feature that was arguably broken. (e.g., define `sport` as `schema:sport` and compact `http://schema.org/sportsEvent`, yielded `sport:sEvent`, when what was desired is `schema:sportsEvent`).

There is currently an issue on compacting literals without language using a language map (using the `@none` index), but this will likely resolve to require 1.1 mode to operate this way.

We can say that a 1.1 processor will "process" (as in expand) a 1.0 document the same as a 1.0 processor, but not, strictly speaking, that all transformations will generate exactly the same results.

**Comment by iherman** [comment]
@gkellogg, I saw the changes, but I think it is way too detailed for a charter. Can we say something like

> When processing legacy JSON-LD documents, JSON-LD processors generate the same expanded output (the only exception is related to an erratum in JSON-LD 1.0 (put reference here)).

Do we have to say anything in the charter about the compact case? I am not sure. The expanded form is the closest to an RDF equivalence, and that is it.

(AC members who will vote on the charter will not really know what we are talking about with the text that is currently in the latest commit...)

**Comment by gkellogg** [comment]
>  but I think it is way too detailed for a charter

I just copied information from the [Changes section](https://json-ld.org/spec/latest/json-ld-api/#changes-since-1-0-recommendation-of-16-january-2014), but sure, I'll change it.

**Comment by gkellogg** [comment]
The expansion case is related to json-ld/json-ld.org#470, which hasn't been, but should be filed as an erratum. I'll update the text to point to the [errata](https://www.w3.org/2001/sw/wiki/JSON_LD_Errata), but we need to get that filed somehow. Would that simply start as an email to public-rdf-comments@w3.org?

To be complete, we should also file json-ld/json-ld.org#405.

**Comment by iherman** [comment]
Yes, we should follow the official errata procedure, which entails that email indeed...
