### ISSUE TITLE
The scope section is probably too verbose

### ISSUE THREAD

**Issue by iherman** [json-ld/charter#8]
I wonder how to make the scope section much more succinct. I am not sure that the detailed bulleted list for the changes should be part of the charter. Let alone the fact that it sounds as if those entries, and their proposed solutions (referred to via the PR-s) are already cast in concrete and the charter takes a commitment. Formally, it will be up to the WG to make those decisions.

Is there a text/blog/presentation (like, e.g., the TPAC presentation) that could be referred to instead, showing the type of solution adopted at this moment by the CG? That could be _referred_ from the charter but not turning these into a WG commitments? 

Cc: @wseltzer

**Comment by wseltzer** [comment]
The scope section should describe the outer bounds of what the group can do. If the group wants to include additional background information in its charter, it might put that into a mission or motivation section, or link to a whitepaper outside the charter itself. 

See https://github.com/w3c/charter-drafts/blob/gh-pages/README.md in the charter-template repo.

**Comment by gkellogg** [comment]
I will reduce it to generally describe addressing issues raised by the community through the mailing list and issue tracker, with a reference to the [TPAC presentation](https://json-ld.org/presentations/JSON-LD-Update-TPAC-2017/assets/player/KeynoteDHTMLPlayer.html#0) for some examples.

I'd like to add more language to generally provide for more compatible changes in this general direction.

There was also a [comment](https://github.com/w3c/strategy/issues/31#issuecomment-259139790) on I18N considerations of text direction, that while I don't think there is a change, should be addressed by the WG and may indicate some explanatory text in the spec.

The WG may also want to re-consider the danger of legacy 1.0 processors misinterpreting new context features, for which the `@version` announcement in the manifest is currently required, as this is a disruptive change that is made redundant by new requirements of processors running in 1.0 mode, which could be detected in less intrusive ways.

And, of course, new stake holders may come forward in the charter review period with other issues for the group to consider.
